version: '3'
services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    # user: "${UID}:${GID}"
    networks:
      - "portainer_traefik"
    volumes:
      - filebrowser:/config
      - velocity:/data/velocity
      - survival:/data/survival
      - build:/data/build
      - dev:/data/dev
      - archive:/data/archive
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`files.{{ internal_domain_root }}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

  velocity:
    image: ghcr.io/mineinabyss/proxy:master
    container_name: velocity
    networks:
      - minecraft
    ports:
      - 25565:25577
    volumes:
      - velocity
    environment:
      SERVER_NAME: "velocity"
      TYPE: VELOCITY
      MEMORY: "512m"
      ANSIBLE_PULL_BRANCH: develop

  survival:
    image: ghcr.io/mineinabyss/minecraft:master
    container_name: minecraft-survival
    networks:
      - minecraft
    environment:
      SERVER_NAME: "survival"
      ANSIBLE_PULL_BRANCH: "develop"
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
#      EXEC_DIRECTLY: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      MEMORY: "4G"
    volumes:
      - survival:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

#  backup:
#    image: itzg/mc-backup
#    environment:
#      RCON_HOST: mc
#      BACKUP_METHOD: restic
#      RESTIC_PASSWORD: password
#      RESTIC_REPOSITORY: rclone:CFG_NAME:BUCKET_NAME
#    volumes:
#      # mount volume pre-configured using a host mounted file
#      - ./rclone.conf:/config/rclone/rclone.conf
#      # or configure one into a named volume using
#      # docker run -it --rm -v rclone-config:/config/rclone rclone/rclone config
#      # and change the above to
#      # - rclone-config:/config/rclone
#      - mc:/data:ro
#      - backups:/backup


volumes:
  filebrowser:
  velocity:
  survival:
  build:
  dev:
  archive:

networks:
  minecraft:
  portainer_traefik:
    external: true
