version: '3'
services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    networks:
      - "portainer_traefik"
    volumes:
      - "{{ docker_dir }}/filebrowser:/config"
      - "{{ docker_dir }}/minecraft:/data/minecraft"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.{{ internal_domain_root }}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=8080"
      - "traefik.http.routers.filebrowser.service=frontend"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser.middlewares=oauth@docker"

  velocity:
    image: ghcr.io/mineinabyss/proxy:master
    container_name: velocity
    networks:
      - minecraft
    ports:
      - "25565:25577"
    volumes:
      - "{{ docker_dir }}/minecraft/velocity:/server"
      - "{{ docker_dir }}/server-configs/velocity:/server-config"
    environment:
      SERVER_NAME: "velocity"
      TYPE: VELOCITY
      MEMORY: "512m"
      ANSIBLE_PULL_BRANCH: develop
    restart: unless-stopped
    secrets:
      - velocity_forwarding_secret

  minecraft-survival:
    image: ghcr.io/mineinabyss/minecraft:master
    networks:
      - minecraft
    environment:
      SERVER_NAME: "survival"
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
      #      EXEC_DIRECTLY: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      MEMORY: "4G"
      ANSIBLE_PULL_BRANCH: templates
      ONLINE_MODE: "false"
    volumes:
      - "{{ docker_dir }}/minecraft/survival:/data"
      - "{{ docker_dir }}/server-configs/papermc:/server-config"
    tty: true
    stdin_open: true
    restart: unless-stopped
    secrets:
      - velocity_forwarding_secret

#  backup:
#    image: itzg/mc-backup
#    environment:
#      RCON_HOST: mc
#      BACKUP_METHOD: restic
#      RESTIC_PASSWORD: password
#      RESTIC_REPOSITORY: rclone:CFG_NAME:BUCKET_NAME
#    volumes:
#      # mount volume pre-configured using a host mounted file
#      - ./rclone.conf:/config/rclone/rclone.conf
#      # or configure one into a named volume using
#      # docker run -it --rm -v rclone-config:/config/rclone rclone/rclone config
#      # and change the above to
#      # - rclone-config:/config/rclone
#      - mc:/data:ro
#      - backups:/backup


volumes:
  filebrowser:

networks:
  minecraft:
  portainer_traefik:
    external: true

secrets:
  velocity_forwarding_secret:
    file: "{{ docker_compose_dir }}/secrets/velocity_forwarding_secret"
