providers:
  docker:
    exposedByDefault: false
  file:
    directory: conf.d

certificatesResolvers:
  letsencrypt:
    acme:
      dnsChallenge:
        provider: cloudflare
      email: "{{ cloudflare_email }}"
      storage: "/acme_data/acme.json"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "{{ domain_root }}"
            sans:
              - "*.{{ domain_root }}"
