- hosts: "root"
  become: yes
  pre_tasks:
    - include_vars:
        file: "local/user-config.yml"
    - include_vars:
        file: "{{ vault_location }}"
  roles:
    - role: system
    - role: geerlingguy.security
    - role: nickjj.docker
    - name: containers
