version: '3.2'

services:
  traefik:
    container_name: traefik
    restart: always
    image: "traefik:latest"
    networks:
      - traefik
    environment:
      CLOUDFLARE_EMAIL: "{{ cloudflare_email }}"
      CLOUDFLARE_API_KEY: "{{ cloudflare_api_key }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme_data:/acme_data/"
      - "{{ docker_compose_dir }}/config/traefik/traefik.yml:/traefik.yml"
      - "{{ docker_compose_dir }}/config/traefik/conf.d:/conf.d"

  agent:
    image: portainer/agent
    restart: always
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: "portainer/portainer-ee:sts"
    restart: always
    networks:
      - traefik
    command: -H tcp://agent:9001 --tlsskipverify
    labels:
      # Frontend
      traefik.enable: true
      traefik.http.services.frontend.loadbalancer.server.port: 9000
      traefik.http.routers.frontend.rule: Host(`panel.{{ internal_domain_root }}`)
      traefik.http.routers.frontend.entrypoints: websecure
      traefik.http.routers.frontend.tls.certresolver: letsencrypt
#      traefik.http.routers.frontend.middlewares: oauth@docker
      traefik.http.routers.frontend.service: frontend
    volumes:
      - portainer_data:/data

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_MONITOR_ONLY: "true"
volumes:
  portainer_data:
  acme_data:

networks:
  traefik:
