hostname: '{{ inventory_hostname }}'
timezone: 	America/Toronto
ntp_timezone: '{{ timezone }}'
locale: en_US.UTF-8
keyboard_layout: us

# SSH (geerlingguy.security)
security_ssh_port: 17072
security_sudoers_passworded: "{{ ssh_users | map(attribute='name') | list }}"
security_autoupdate_reboot_time: '03:00'

# Packages
extra_packages:
  - fish
  - htop
  - git
  - rsync
  - ncdu

# Docker apps
docker_dir: /opt/docker/data
docker_compose_dir: /opt/docker/compose
docker_user: docker
docker_user_uid: 1000

services_remove_orphans: true
shell: /usr/bin/fish

# Traefik and oauth config
#internal_domain_root: internal.mineinabyss.com
internal_domain_root: localhost
oauth2_proxy_public:
  enabled: true
  github_org: 'MineInAbyss'
  github_teams: 'staff' # Comma separated global team whitelist
