version: '2'
x-labels-homepage: &default-homepage
  homepage.group: Minecraft
  homepage.icon: minecraft.png
  homepage.showStats: 'true'

x-labels-daily-restarts: &daily-restarts
  ofelia.enabled: "true"
  ofelia.job-exec.restart.schedule: "0 1 * * *"
  ofelia.job-exec.restart.command: ${RESTART_COMMAND}

x-service-velocity-defaults: &velocity-network
  networks:
    - minecraft
  restart: unless-stopped
  tty: true
  stdin_open: true
  secrets:
    - velocity_forwarding_secret

x-environment-minecraft-defaults: &minecraft-env-defaults
  EULA: "TRUE"
  TYPE: "PAPER"
  EXEC_DIRECTLY: "TRUE"
  USE_AIKAR_FLAGS: "TRUE"
  ONLINE_MODE: "FALSE"

services:

  velocity:
    <<: *velocity-network
    image: ghcr.io/mineinabyss/proxy:master
    cpuset: '0-1'
    ports:
      - "25565:25577"
    volumes:
      - "${DIR_MINECRAFT}/velocity:/server"
      - "${DIR_CONFIGS}/velocity:/server-config"
    environment:
      SERVER_NAME: "velocity"
      TYPE: VELOCITY
      MEMORY: "512m"
      ANSIBLE_PULL_BRANCH: develop
    labels:
      <<: *default-homepage
      homepage.name: Velocity

  minecraft-dev:
    <<: *velocity-network
    image: ghcr.io/mineinabyss/minecraft:master
    cpuset: '2-3'
    networks:
      - minecraft
    environment:
      <<: *minecraft-env-defaults
      SERVER_NAME: "dev"
      VERSION: "1.20.1"
      MEMORY: "4G"
      ANSIBLE_PULL_BRANCH: templates
    volumes:
      - "${DIR_MINECRAFT}/dev:/data"
      - "${DIR_CONFIGS}/dev:/server-config"
    labels:
      <<: [*default-homepage, *daily-restarts]
      homepage.name: Dev

  backup-dev:
    image: itzg/mc-backup
    environment:
      RCON_HOST: minecraft-dev
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_REPOSITORY: rclone:backup:dev
    volumes:
      - /opt/docker/compose/secrets/rclone.conf:/config/rclone/rclone.conf:ro
      - /opt/docker/data/minecraft/dev/world:/data:ro
      - /opt/docker/compose/secrets/rclone.conf:/config/rclone/rclone.conf
      - backup-dev:/backup

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - minecraft-dev
      - velocity
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  filebrowser:
  backup-dev:

networks:
  minecraft:
  compose_traefik:
    external: true

secrets:
  velocity_forwarding_secret:
    file: "/opt/docker/compose/secrets/velocity_forwarding_secret"
