- name: "Create login user: {{ username }}"
  user:
    name: "{{ username }}"
    password: "{{ password_hash }}"
    groups:
#      - "{{ sudo_group }}"
    state: present
    shell: "{{ shell }}"
    append: true

- name: "Authorize their SSH key"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ authorized_key }}"
