- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"
#    - "{{ docker_compose_dir }}/secrets"

- name: Create template directories
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item.path }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
#    mode: '{{ item.mode }}'
  with_community.general.filetree: templates/
  when: item.state == 'directory'

- name: Copy templates to docker compose dir
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_compose_dir }}/{{ item.path }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
  with_filetree: "templates/"
  when: item.state == 'file'

- name: Check if velocity forwarding secret exists
  ansible.builtin.stat:
    path: "{{ docker_compose_dir }}/secrets/velocity_forwarding_secret"
  register: secret_file

- name: Generate forwarding secret
  shell:
    cmd: "openssl rand -hex 32 > secrets/velocity_forwarding_secret"
    chdir: "{{ docker_compose_dir }}"
  when: secret_file.stat.exists == False

- name: Docker-compose pull
  shell:
    cmd: "docker-compose pull"
    chdir: "{{ docker_compose_dir }}"

- name: Docker-compose up
  shell:
    cmd: "docker-compose up --remove-orphans -d"
    chdir: "{{ docker_compose_dir }}"
