http:
  middlewares:
    oauth:
      chain:
        middlewares:
          - oauth-signin
          - oauth-verify
    oauth-verify:
      forwardAuth:
        address: "http://oauth2proxy:4180/oauth2/auth"
        authResponseHeaders: "X-Auth-Request-Preferred-Username, X-Auth-Request-User, X-Auth-Request-Email"
    oauth-signin:
      errors:
        service: route-authproxy@docker
        status: "401"
        query: "/oauth2/sign_in"
